# Generated by Django 4.1.2 on 2023-04-24 17:48

import apolloapi.common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "firebase_project_id",
                    models.CharField(
                        blank=True,
                        help_text="Firebase project id",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "firebase_database_url",
                    models.CharField(
                        blank=True,
                        help_text="firebase database url",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "firebase_service_account_key",
                    models.TextField(
                        blank=True, help_text="service account key", null=True
                    ),
                ),
                (
                    "connection_string",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "engine",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "apiRequestType",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Post", "Post"),
                            ("Patch", "Patch"),
                            ("Put", "Put"),
                            ("Delete", "Delete"),
                            ("Get", "Get"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("queryParam", models.TextField(blank=True, default="", null=True)),
                ("header", models.TextField(blank=True, default="", null=True)),
                (
                    "authType",
                    models.CharField(
                        choices=[("None", "None"), ("Basic_auth", "Basic")],
                        default="none",
                        max_length=200,
                    ),
                ),
                ("auth", models.TextField(blank=True, default="", null=True)),
                ("base_url", models.TextField(blank=True, default="", null=True)),
                ("jsonBody", models.TextField(blank=True, default="", null=True)),
                (
                    "actionType",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=apolloapi.common.utils.str_uid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("resourceName", models.CharField(max_length=100, unique=True)),
                (
                    "resourceType",
                    models.CharField(
                        choices=[
                            ("Postgres", "Postgres"),
                            ("Firebase", "Firebase"),
                            ("Rest", "Rest"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "resourcePrefix",
                    models.CharField(choices=[("CLI", "Cli")], max_length=100),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
