# Generated by Django 4.1.2 on 2023-04-24 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="groups",
            field=models.ForeignKey(
                default="",
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.group",
            ),
            preserve_default=False,
        ),
    ]
