# Generated by Django 4.1.2 on 2023-04-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_integration_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integration",
            name="groups",
        ),
    ]
